// <auto-generated />
using Case.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Case.Migrations
{
    [DbContext(typeof(MyWebApiContext))]
    [Migration("20210424170822_Case")]
    partial class Case
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Case.Model.LeaderBoards", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("countr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<int>("rank")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("LeaderBoards");
                });

            modelBuilder.Entity("Case.Model.Scores", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<float>("score_worth")
                        .HasColumnType("real");

                    b.Property<int>("timestamp")
                        .HasColumnType("integer");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Case.Model.Users", b =>
                {
                    b.Property<string>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<int>("rank")
                        .HasColumnType("integer");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
